baseURL = 'https://neodrain.net/'
languageCode = 'en-us'
title = 'FEED'
theme = 'typo'

[taxonomies]
tag = 'tags'


[params]
# Meta description
description = "Just another place on the net."

# Appearance settings
theme = 'dark'
colorPalette = 'default'
hideBackToTop = true
hidePagination = true
hideHeader = false


# Collection to display on home
homeCollectionTitle = ''
homeCollection = 'posts'

# Lists parameters
paginationSize = 1000
listSummaries = false
listDateFormat = '02-01-06'

# Breadcrumbs
breadcrumbs = false

showFooter = false

# Main menu pages
#[[params.menu]]
#name = "home"
#url = "/"

#[[params.menu]]
#name = "feed"
#url = "/posts"

#[[params.menu]]
#name = "about"
#url = "/about"

# Syntax highligth on code blocks
[markup]
[markup.highlight]
style = 'algol'


